In [128]:
import numpy as np
import scipy

In [129]:
data = np.load('user_movie_rating.npy')
users = data[:,0]
movies = data[:,1]
ranking = data[:,2]

matrix = scipy.sparse.csr_matrix((ranking, [users, movies]))
print(matrix)

  (1, 30)	3
  (1, 157)	3
  (1, 173)	4
  (1, 175)	5
  (1, 191)	2
  (1, 197)	3
  (1, 241)	3
  (1, 295)	4
  (1, 299)	3
  (1, 329)	4
  (1, 361)	3
  (1, 445)	3
  (1, 457)	5
  (1, 468)	3
  (1, 494)	3
  (1, 501)	3
  (1, 528)	4
  (1, 564)	4
  (1, 580)	3
  (1, 658)	3
  (1, 705)	3
  (1, 706)	3
  (1, 723)	3
  (1, 788)	3
  (1, 825)	3
  :	:
  (103703, 16552)	4
  (103703, 16604)	4
  (103703, 16668)	4
  (103703, 16707)	3
  (103703, 16740)	2
  (103703, 16765)	2
  (103703, 16830)	5
  (103703, 16882)	3
  (103703, 16922)	3
  (103703, 16954)	4
  (103703, 17053)	4
  (103703, 17088)	1
  (103703, 17149)	2
  (103703, 17154)	3
  (103703, 17157)	5
  (103703, 17251)	2
  (103703, 17308)	3
  (103703, 17330)	2
  (103703, 17346)	4
  (103703, 17424)	4
  (103703, 17479)	2
  (103703, 17621)	4
  (103703, 17622)	2
  (103703, 17627)	4
  (103703, 17764)	4


In [130]:
print(np.shape(matrix))
num_users = max(users)
num_movies = max(movies)

(103704, 17771)


In [131]:
permutations = []
for i in range(100):
    permutations +=[np.random.permutation(num_movies+1)]

In [133]:
signatures = np.zeros((100,num_users+1),dtype=int)
for num, permutation in enumerate(permutations):
    for user in range(1,num_users+1): 
        movies = matrix[user].indices
        signatures[num,user] = np.min(permutation[movies])
signatures = signatures[:,1:]

In [134]:
print(signatures)

[[  4   4   4 ...   9   4   4]
 [ 18  18  49 ...  72  49  49]
 [ 39   7  39 ...  26  39  39]
 ...
 [ 30   2 112 ...  53  68  69]
 [ 24  24  24 ... 108  24  24]
 [ 41  27  15 ...  15  32  60]]
